addSbtPlugin("com.jsuereth"       % "sbt-pgp"                  % "1.1.1")
addSbtPlugin("com.github.gseitz"  % "sbt-release"              % "1.0.8")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "0.14.6")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.5.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.23")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalajs-bundler"      % "0.13.0")