package info.mukel.telegrambot4s.models

import scala.language.implicitConversions

object Country extends Enumeration {
  type Country = Value
  sealed case class ISOCountry(
                                code        : String,
                                englishName : String) extends Val(code)

  implicit def valueToCountry(v: Value): ISOCountry = v.asInstanceOf[ISOCountry]

  val AD = ISOCountry(code = "AD", englishName = "Andorra")
  val AE = ISOCountry(code = "AE", englishName = "United Arab Emirates")
  val AF = ISOCountry(code = "AF", englishName = "Afghanistan")
  val AG = ISOCountry(code = "AG", englishName = "Antigua and Barbuda")
  val AI = ISOCountry(code = "AI", englishName = "Anguilla")
  val AL = ISOCountry(code = "AL", englishName = "Albania")
  val AM = ISOCountry(code = "AM", englishName = "Armenia")
  val AN = ISOCountry(code = "AN", englishName = "Netherlands Antilles")
  val AO = ISOCountry(code = "AO", englishName = "Angola")
  val AQ = ISOCountry(code = "AQ", englishName = "Antarctica")
  val AR = ISOCountry(code = "AR", englishName = "Argentina")
  val AS = ISOCountry(code = "AS", englishName = "American Samoa")
  val AT = ISOCountry(code = "AT", englishName = "Austria")
  val AU = ISOCountry(code = "AU", englishName = "Australia")
  val AW = ISOCountry(code = "AW", englishName = "Aruba")
  val AX = ISOCountry(code = "AX", englishName = "Åland Islands")
  val AZ = ISOCountry(code = "AZ", englishName = "Azerbaijan")
  val BA = ISOCountry(code = "BA", englishName = "Bosnia and Herzegovina")
  val BB = ISOCountry(code = "BB", englishName = "Barbados")
  val BD = ISOCountry(code = "BD", englishName = "Bangladesh")
  val BE = ISOCountry(code = "BE", englishName = "Belgium")
  val BF = ISOCountry(code = "BF", englishName = "Burkina Faso")
  val BG = ISOCountry(code = "BG", englishName = "Bulgaria")
  val BH = ISOCountry(code = "BH", englishName = "Bahrain")
  val BI = ISOCountry(code = "BI", englishName = "Burundi")
  val BJ = ISOCountry(code = "BJ", englishName = "Benin")
  val BL = ISOCountry(code = "BL", englishName = "Saint Barthélemy")
  val BM = ISOCountry(code = "BM", englishName = "Bermuda")
  val BN = ISOCountry(code = "BN", englishName = "Brunei")
  val BO = ISOCountry(code = "BO", englishName = "Bolivia")
  val BQ = ISOCountry(code = "BQ", englishName = "Bonaire, Sint Eustatius and Saba")
  val BR = ISOCountry(code = "BR", englishName = "Brazil")
  val BS = ISOCountry(code = "BS", englishName = "Bahamas")
  val BT = ISOCountry(code = "BT", englishName = "Bhutan")
  val BV = ISOCountry(code = "BV", englishName = "Bouvet Island")
  val BW = ISOCountry(code = "BW", englishName = "Botswana")
  val BY = ISOCountry(code = "BY", englishName = "Belarus")
  val BZ = ISOCountry(code = "BZ", englishName = "Belize")
  val CA = ISOCountry(code = "CA", englishName = "Canada")
  val CC = ISOCountry(code = "CC", englishName = "Cocos Islands")
  val CD = ISOCountry(code = "CD", englishName = "The Democratic Republic Of Congo")
  val CF = ISOCountry(code = "CF", englishName = "Central African Republic")
  val CG = ISOCountry(code = "CG", englishName = "Congo")
  val CH = ISOCountry(code = "CH", englishName = "Switzerland")
  val CI = ISOCountry(code = "CI", englishName = "Côte d'Ivoire")
  val CK = ISOCountry(code = "CK", englishName = "Cook Islands")
  val CL = ISOCountry(code = "CL", englishName = "Chile")
  val CM = ISOCountry(code = "CM", englishName = "Cameroon")
  val CN = ISOCountry(code = "CN", englishName = "China")
  val CO = ISOCountry(code = "CO", englishName = "Colombia")
  val CR = ISOCountry(code = "CR", englishName = "Costa Rica")
  val CU = ISOCountry(code = "CU", englishName = "Cuba")
  val CV = ISOCountry(code = "CV", englishName = "Cape Verde")
  val CW = ISOCountry(code = "CW", englishName = "Curaçao")
  val CX = ISOCountry(code = "CX", englishName = "Christmas Island")
  val CY = ISOCountry(code = "CY", englishName = "Cyprus")
  val CZ = ISOCountry(code = "CZ", englishName = "Czech Republic")
  val DE = ISOCountry(code = "DE", englishName = "Germany")
  val DJ = ISOCountry(code = "DJ", englishName = "Djibouti")
  val DK = ISOCountry(code = "DK", englishName = "Denmark")
  val DM = ISOCountry(code = "DM", englishName = "Dominica")
  val DO = ISOCountry(code = "DO", englishName = "Dominican Republic")
  val DZ = ISOCountry(code = "DZ", englishName = "Algeria")
  val EC = ISOCountry(code = "EC", englishName = "Ecuador")
  val EE = ISOCountry(code = "EE", englishName = "Estonia")
  val EG = ISOCountry(code = "EG", englishName = "Egypt")
  val EH = ISOCountry(code = "EH", englishName = "Western Sahara")
  val ER = ISOCountry(code = "ER", englishName = "Eritrea")
  val ES = ISOCountry(code = "ES", englishName = "Spain")
  val ET = ISOCountry(code = "ET", englishName = "Ethiopia")
  val FI = ISOCountry(code = "FI", englishName = "Finland")
  val FJ = ISOCountry(code = "FJ", englishName = "Fiji")
  val FK = ISOCountry(code = "FK", englishName = "Falkland Islands")
  val FM = ISOCountry(code = "FM", englishName = "Micronesia")
  val FO = ISOCountry(code = "FO", englishName = "Faroe Islands")
  val FR = ISOCountry(code = "FR", englishName = "France")
  val GA = ISOCountry(code = "GA", englishName = "Gabon")
  val GB = ISOCountry(code = "GB", englishName = "United Kingdom")
  val GD = ISOCountry(code = "GD", englishName = "Grenada")
  val GE = ISOCountry(code = "GE", englishName = "Georgia")
  val GF = ISOCountry(code = "GF", englishName = "French Guiana")
  val GG = ISOCountry(code = "GG", englishName = "Guernsey")
  val GH = ISOCountry(code = "GH", englishName = "Ghana")
  val GI = ISOCountry(code = "GI", englishName = "Gibraltar")
  val GL = ISOCountry(code = "GL", englishName = "Greenland")
  val GM = ISOCountry(code = "GM", englishName = "Gambia")
  val GN = ISOCountry(code = "GN", englishName = "Guinea")
  val GP = ISOCountry(code = "GP", englishName = "Guadeloupe")
  val GQ = ISOCountry(code = "GQ", englishName = "Equatorial Guinea")
  val GR = ISOCountry(code = "GR", englishName = "Greece")
  val GS = ISOCountry(code = "GS", englishName = "South Georgia And The South Sandwich Islands")
  val GT = ISOCountry(code = "GT", englishName = "Guatemala")
  val GU = ISOCountry(code = "GU", englishName = "Guam")
  val GW = ISOCountry(code = "GW", englishName = "Guinea-Bissau")
  val GY = ISOCountry(code = "GY", englishName = "Guyana")
  val HK = ISOCountry(code = "HK", englishName = "Hong Kong")
  val HM = ISOCountry(code = "HM", englishName = "Heard Island And McDonald Islands")
  val HN = ISOCountry(code = "HN", englishName = "Honduras")
  val HR = ISOCountry(code = "HR", englishName = "Croatia")
  val HT = ISOCountry(code = "HT", englishName = "Haiti")
  val HU = ISOCountry(code = "HU", englishName = "Hungary")
  val ID = ISOCountry(code = "ID", englishName = "Indonesia")
  val IE = ISOCountry(code = "IE", englishName = "Ireland")
  val IL = ISOCountry(code = "IL", englishName = "Israel")
  val IM = ISOCountry(code = "IM", englishName = "Isle Of Man")
  val IN = ISOCountry(code = "IN", englishName = "India")
  val IO = ISOCountry(code = "IO", englishName = "British Indian Ocean Territory")
  val IQ = ISOCountry(code = "IQ", englishName = "Iraq")
  val IR = ISOCountry(code = "IR", englishName = "Iran")
  val IS = ISOCountry(code = "IS", englishName = "Iceland")
  val IT = ISOCountry(code = "IT", englishName = "Italy")
  val JE = ISOCountry(code = "JE", englishName = "Jersey")
  val JM = ISOCountry(code = "JM", englishName = "Jamaica")
  val JO = ISOCountry(code = "JO", englishName = "Jordan")
  val JP = ISOCountry(code = "JP", englishName = "Japan")
  val KE = ISOCountry(code = "KE", englishName = "Kenya")
  val KG = ISOCountry(code = "KG", englishName = "Kyrgyzstan")
  val KH = ISOCountry(code = "KH", englishName = "Cambodia")
  val KI = ISOCountry(code = "KI", englishName = "Kiribati")
  val KM = ISOCountry(code = "KM", englishName = "Comoros")
  val KN = ISOCountry(code = "KN", englishName = "Saint Kitts And Nevis")
  val KP = ISOCountry(code = "KP", englishName = "North Korea")
  val KR = ISOCountry(code = "KR", englishName = "South Korea")
  val KW = ISOCountry(code = "KW", englishName = "Kuwait")
  val KY = ISOCountry(code = "KY", englishName = "Cayman Islands")
  val KZ = ISOCountry(code = "KZ", englishName = "Kazakhstan")
  val LA = ISOCountry(code = "LA", englishName = "Laos")
  val LB = ISOCountry(code = "LB", englishName = "Lebanon")
  val LC = ISOCountry(code = "LC", englishName = "Saint Lucia")
  val LI = ISOCountry(code = "LI", englishName = "Liechtenstein")
  val LK = ISOCountry(code = "LK", englishName = "Sri Lanka")
  val LR = ISOCountry(code = "LR", englishName = "Liberia")
  val LS = ISOCountry(code = "LS", englishName = "Lesotho")
  val LT = ISOCountry(code = "LT", englishName = "Lithuania")
  val LU = ISOCountry(code = "LU", englishName = "Luxembourg")
  val LV = ISOCountry(code = "LV", englishName = "Latvia")
  val LY = ISOCountry(code = "LY", englishName = "Libya")
  val MA = ISOCountry(code = "MA", englishName = "Morocco")
  val MC = ISOCountry(code = "MC", englishName = "Monaco")
  val MD = ISOCountry(code = "MD", englishName = "Moldova")
  val ME = ISOCountry(code = "ME", englishName = "Montenegro")
  val MF = ISOCountry(code = "MF", englishName = "Saint Martin")
  val MG = ISOCountry(code = "MG", englishName = "Madagascar")
  val MH = ISOCountry(code = "MH", englishName = "Marshall Islands")
  val MK = ISOCountry(code = "MK", englishName = "Macedonia")
  val ML = ISOCountry(code = "ML", englishName = "Mali")
  val MM = ISOCountry(code = "MM", englishName = "Myanmar")
  val MN = ISOCountry(code = "MN", englishName = "Mongolia")
  val MO = ISOCountry(code = "MO", englishName = "Macao")
  val MP = ISOCountry(code = "MP", englishName = "Northern Mariana Islands")
  val MQ = ISOCountry(code = "MQ", englishName = "Martinique")
  val MR = ISOCountry(code = "MR", englishName = "Mauritania")
  val MS = ISOCountry(code = "MS", englishName = "Montserrat")
  val MT = ISOCountry(code = "MT", englishName = "Malta")
  val MU = ISOCountry(code = "MU", englishName = "Mauritius")
  val MV = ISOCountry(code = "MV", englishName = "Maldives")
  val MW = ISOCountry(code = "MW", englishName = "Malawi")
  val MX = ISOCountry(code = "MX", englishName = "Mexico")
  val MY = ISOCountry(code = "MY", englishName = "Malaysia")
  val MZ = ISOCountry(code = "MZ", englishName = "Mozambique")
  val NA = ISOCountry(code = "NA", englishName = "Namibia")
  val NC = ISOCountry(code = "NC", englishName = "New Caledonia")
  val NE = ISOCountry(code = "NE", englishName = "Niger")
  val NF = ISOCountry(code = "NF", englishName = "Norfolk Island")
  val NG = ISOCountry(code = "NG", englishName = "Nigeria")
  val NI = ISOCountry(code = "NI", englishName = "Nicaragua")
  val NL = ISOCountry(code = "NL", englishName = "Netherlands")
  val NO = ISOCountry(code = "NO", englishName = "Norway")
  val NP = ISOCountry(code = "NP", englishName = "Nepal")
  val NR = ISOCountry(code = "NR", englishName = "Nauru")
  val NU = ISOCountry(code = "NU", englishName = "Niue")
  val NZ = ISOCountry(code = "NZ", englishName = "New Zealand")
  val OM = ISOCountry(code = "OM", englishName = "Oman")
  val PA = ISOCountry(code = "PA", englishName = "Panama")
  val PE = ISOCountry(code = "PE", englishName = "Peru")
  val PF = ISOCountry(code = "PF", englishName = "French Polynesia")
  val PG = ISOCountry(code = "PG", englishName = "Papua New Guinea")
  val PH = ISOCountry(code = "PH", englishName = "Philippines")
  val PK = ISOCountry(code = "PK", englishName = "Pakistan")
  val PL = ISOCountry(code = "PL", englishName = "Poland")
  val PM = ISOCountry(code = "PM", englishName = "Saint Pierre And Miquelon")
  val PN = ISOCountry(code = "PN", englishName = "Pitcairn")
  val PR = ISOCountry(code = "PR", englishName = "Puerto Rico")
  val PS = ISOCountry(code = "PS", englishName = "Palestine")
  val PT = ISOCountry(code = "PT", englishName = "Portugal")
  val PW = ISOCountry(code = "PW", englishName = "Palau")
  val PY = ISOCountry(code = "PY", englishName = "Paraguay")
  val QA = ISOCountry(code = "QA", englishName = "Qatar")
  val RE = ISOCountry(code = "RE", englishName = "Reunion")
  val RO = ISOCountry(code = "RO", englishName = "Romania")
  val RS = ISOCountry(code = "RS", englishName = "Serbia")
  val RU = ISOCountry(code = "RU", englishName = "Russia")
  val RW = ISOCountry(code = "RW", englishName = "Rwanda")
  val SA = ISOCountry(code = "SA", englishName = "Saudi Arabia")
  val SB = ISOCountry(code = "SB", englishName = "Solomon Islands")
  val SC = ISOCountry(code = "SC", englishName = "Seychelles")
  val SD = ISOCountry(code = "SD", englishName = "Sudan")
  val SE = ISOCountry(code = "SE", englishName = "Sweden")
  val SG = ISOCountry(code = "SG", englishName = "Singapore")
  val SH = ISOCountry(code = "SH", englishName = "Saint Helena")
  val SI = ISOCountry(code = "SI", englishName = "Slovenia")
  val SJ = ISOCountry(code = "SJ", englishName = "Svalbard And Jan Mayen")
  val SK = ISOCountry(code = "SK", englishName = "Slovakia")
  val SL = ISOCountry(code = "SL", englishName = "Sierra Leone")
  val SM = ISOCountry(code = "SM", englishName = "San Marino")
  val SN = ISOCountry(code = "SN", englishName = "Senegal")
  val SO = ISOCountry(code = "SO", englishName = "Somalia")
  val SR = ISOCountry(code = "SR", englishName = "Suriname")
  val SS = ISOCountry(code = "SS", englishName = "South Sudan")
  val ST = ISOCountry(code = "ST", englishName = "Sao Tome And Principe")
  val SV = ISOCountry(code = "SV", englishName = "El Salvador")
  val SX = ISOCountry(code = "SX", englishName = "Sint Maarten (Dutch part)")
  val SY = ISOCountry(code = "SY", englishName = "Syria")
  val SZ = ISOCountry(code = "SZ", englishName = "Swaziland")
  val TC = ISOCountry(code = "TC", englishName = "Turks And Caicos Islands")
  val TD = ISOCountry(code = "TD", englishName = "Chad")
  val TF = ISOCountry(code = "TF", englishName = "French Southern Territories")
  val TG = ISOCountry(code = "TG", englishName = "Togo")
  val TH = ISOCountry(code = "TH", englishName = "Thailand")
  val TJ = ISOCountry(code = "TJ", englishName = "Tajikistan")
  val TK = ISOCountry(code = "TK", englishName = "Tokelau")
  val TL = ISOCountry(code = "TL", englishName = "Timor-Leste")
  val TM = ISOCountry(code = "TM", englishName = "Turkmenistan")
  val TN = ISOCountry(code = "TN", englishName = "Tunisia")
  val TO = ISOCountry(code = "TO", englishName = "Tonga")
  val TR = ISOCountry(code = "TR", englishName = "Turkey")
  val TT = ISOCountry(code = "TT", englishName = "Trinidad and Tobago")
  val TV = ISOCountry(code = "TV", englishName = "Tuvalu")
  val TW = ISOCountry(code = "TW", englishName = "Taiwan")
  val TZ = ISOCountry(code = "TZ", englishName = "Tanzania")
  val UA = ISOCountry(code = "UA", englishName = "Ukraine")
  val UG = ISOCountry(code = "UG", englishName = "Uganda")
  val UM = ISOCountry(code = "UM", englishName = "United States Minor Outlying Islands")
  val US = ISOCountry(code = "US", englishName = "United States")
  val UY = ISOCountry(code = "UY", englishName = "Uruguay")
  val UZ = ISOCountry(code = "UZ", englishName = "Uzbekistan")
  val VA = ISOCountry(code = "VA", englishName = "Vatican")
  val VC = ISOCountry(code = "VC", englishName = "Saint Vincent And The Grenadines")
  val VE = ISOCountry(code = "VE", englishName = "Venezuela")
  val VG = ISOCountry(code = "VG", englishName = "British Virgin Islands")
  val VI = ISOCountry(code = "VI", englishName = "U.S. Virgin Islands")
  val VN = ISOCountry(code = "VN", englishName = "Vietnam")
  val VU = ISOCountry(code = "VU", englishName = "Vanuatu")
  val WF = ISOCountry(code = "WF", englishName = "Wallis And Futuna")
  val WS = ISOCountry(code = "WS", englishName = "Samoa")
  val YE = ISOCountry(code = "YE", englishName = "Yemen")
  val YT = ISOCountry(code = "YT", englishName = "Mayotte")
  val ZA = ISOCountry(code = "ZA", englishName = "South Africa")
  val ZM = ISOCountry(code = "ZM", englishName = "Zambia")
  val ZW = ISOCountry(code = "ZW", englishName = "Zimbabwe")
}